name: mlops-example-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          permissions: write-all
        run: |
          pip install -r requirements.txt
          python model.py

          echo "##Model Metrics" >> report.md
          cat metrics.txt >> report.md
          cml comment create report.md
